# Generated by Django 5.2.7 on 2026-06-20 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('medecins', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('adresse', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bâtiment',
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('etage', models.IntegerField(default=0)),
                ('capacite', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Chambre',
            },
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_sortie_prevue', models.DateField()),
                ('date_sortie_effective', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('transfert', 'En transfert'), ('sortie', 'Sortie effectuée'), ('annulee', 'Annulée')], default='active', max_length=20)),
                ('motif', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medecin_referent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='medecins.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'ordering': ['-date_entree'],
            },
        ),
        migrations.CreateModel(
            name='ConstanteVitale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('tension_systolique', models.PositiveIntegerField(blank=True, null=True)),
                ('tension_diastolique', models.PositiveIntegerField(blank=True, null=True)),
                ('frequence_cardiaque', models.PositiveIntegerField(blank=True, null=True)),
                ('saturation_o2', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('mesure_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constantes_saisies', to='accounts.userprofile')),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='hospitalisation.hospitalisation')),
            ],
            options={
                'verbose_name': 'Constante vitale',
                'ordering': ['-mesure_at'],
            },
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('maintenance', 'Maintenance')], default='disponible', max_length=20)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='hospitalisation.chambre')),
                ('patient_actuel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lit_actuel', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Lit',
                'unique_together': {('chambre', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='lit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='hospitalisation.lit'),
        ),
        migrations.CreateModel(
            name='ServiceHospitalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hospitalisation.batiment')),
            ],
            options={
                'verbose_name': 'Service hospitalier',
                'unique_together': {('batiment', 'code')},
            },
        ),
        migrations.AddField(
            model_name='chambre',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='hospitalisation.servicehospitalier'),
        ),
        migrations.CreateModel(
            name='TransfertService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.TextField(blank=True)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='hospitalisation.hospitalisation')),
                ('lit_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='hospitalisation.lit')),
                ('lit_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='hospitalisation.lit')),
            ],
            options={
                'verbose_name': 'Transfert inter-services',
                'ordering': ['-date_transfert'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chambre',
            unique_together={('service', 'numero')},
        ),
    ]
