services:
  - type: web
    runtime: python
    name: sghl-web
    env: python
    plan: free
    rootDir: toto
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn toto.wsgi:application --bind 0.0.0.0:$PORT"
    preDeployCommand: "python manage.py migrate --noinput && python manage.py seed_demo"
    healthCheckPath: /api/v1/sante/
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: sghl-db
          property: connectionString
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"

databases:
  - name: sghl-db
    plan: free
    databaseName: sghl
    user: sghl
