# Generated by Django 5.2.7 on 2026-06-20 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_consultation_cim10_code_consultation_version'),
        ('hospitalisation', '0001_initial'),
        ('medecins', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'examen",
            },
        ),
        migrations.CreateModel(
            name='CommandeLabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('commandee', 'Commandée'), ('prelevement', 'Prélèvement effectué'), ('affectee', 'Affectée'), ('saisie', 'Résultats saisis'), ('validee', 'Validée'), ('publiee', 'Publiée'), ('annulee', 'Annulée')], default='commandee', max_length=20)),
                ('numero_commande', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.hospitalisation')),
                ('medecin_prescripteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medecins.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_labo', to='patients.patient')),
                ('type_examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratoire.typeexamen')),
            ],
            options={
                'verbose_name': 'Commande laboratoire',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prelevement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prelevement', models.DateTimeField(default=django.utils.timezone.now)),
                ('echantillon_id', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prelevement', to='laboratoire.commandelabo')),
                ('preleveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prélèvement',
            },
        ),
        migrations.CreateModel(
            name='ResultatLabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField()),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date_saisie', models.DateTimeField(default=django.utils.timezone.now)),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('publie', models.BooleanField(default=False)),
                ('rapport_pdf', models.FileField(blank=True, null=True, upload_to='labo/rapports/')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='laboratoire.commandelabo')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_saisis', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résultat laboratoire',
            },
        ),
    ]
