# Generated by Django 5.2.7 on 2026-06-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('medecin', 'Médecin'), ('infirmier', 'Infirmier(ère)'), ('biologiste', 'Biologiste'), ('pharmacien', 'Pharmacien'), ('comptable', 'Comptable'), ('secretaire', 'Secrétaire'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
