# Generated by Django 5.2.7 on 2026-06-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='cim10_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code CIM-10'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
