# Generated by Django 5.2.7 on 2026-06-20 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_consultation_cim10_code_consultation_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('forme', models.CharField(blank=True, max_length=50)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('seuil_alerte', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Médicament',
            },
        ),
        migrations.CreateModel(
            name='LotMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('date_peremption', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacie.medicament')),
            ],
            options={
                'verbose_name': 'Lot médicament',
                'unique_together': {('medicament', 'numero_lot')},
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('motif', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='pharmacie.lotmedicament')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologie', models.CharField(max_length=255)),
                ('duree_jours', models.PositiveIntegerField(default=7)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('validee_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacie.medicament')),
            ],
            options={
                'verbose_name': 'Prescription',
            },
        ),
    ]
