# Generated by Django 5.2.7 on 2026-05-26 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(choices=[('general', 'General Practitioner'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('obstetrics', 'Obstetrics & Gynecology'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('psychiatry', 'Psychiatry'), ('emergency', 'Emergency Medicine')], max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('years_experience', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Medecins',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
