# Generated by Django 5.2.7 on 2026-05-26 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('monday_hours', models.CharField(default='09:00-17:00', max_length=50)),
                ('tuesday_hours', models.CharField(default='09:00-17:00', max_length=50)),
                ('wednesday_hours', models.CharField(default='09:00-17:00', max_length=50)),
                ('thursday_hours', models.CharField(default='09:00-17:00', max_length=50)),
                ('friday_hours', models.CharField(default='09:00-17:00', max_length=50)),
                ('saturday_hours', models.CharField(default='09:00-13:00', max_length=50)),
                ('sunday_hours', models.CharField(default='Closed', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services.service')),
            ],
            options={
                'ordering': ['service', 'name'],
            },
        ),
    ]
